version: "2"
services:
  rails:
    container_name: sandbox-ecs-rails
    build: .
    env_file: docker/.env
    volumes:
      - .:/data/app
    links:
      - mysql
#      - fluentd
    ports:
      - 3000:3000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.rails

  mysql:
    container_name: sandbox-ecs-mysql
    image: mysql
    env_file: docker/.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  # fluentd:
  #   container_name: sandbox-ecs-fluentd
  #   build: ./docker/fluentd
  #   env_file: docker/.env
  #   # /usr/bin/ruby /usr/local/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
  #   command: sleep 3600
  #   volumes:
  #     - ./docker/fluentd:/fluentd/etc
  #   ports:
  #     - 8080:80
  #     - 24224:24224
