version: "2"
services:
  rails:
    container_name: sandbox-ecs-rails
    build: .
    env_file: .env
    volumes:
      - .:/data/app
    links:
      - mysql
    ports:
      - 3000:3000
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: docker.sandbox_ecs_rails_development
  mysql:
    container_name: sandbox-ecs-mysql
    image: mysql
    env_file: .env
    volumes:
      - ./etc/docker/mysql/data:/var/lib/mysql
      - ./etc/docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
  # fluentd:
  #   container_name: sandbox-ecs-fluentd
  #   build: ./etc/docker/fluentd
  #   env_file: .env
  #   ports:
  #     - 24224:24224
