version: "2"
services:
  rails:
    container_name: sandbox-ecs-rails
    build: .
    env_file: docker/.env
    volumes:
      - .:/data/app
    links:
      - mysql
      - fluentd
    ports:
      - 3000:3000
    logging:
      driver: fluentd

  mysql:
    container_name: sandbox-ecs-mysql
    image: mysql
    env_file: docker/.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  fluentd:
    container_name: sandbox-ecs-fluentd
    image: fluent/fluentd
    env_file: docker/.env
    volumes:
      - ./docker/fluentd:/fluentd/etc
    ports:
      - 24224:24224
