version: "2"
services:
  rails:
    container_name: sandbox-ecs-rails
    build: .
    env_file: docker/.env
    volumes:
      - .:/data/app
    links:
      - mysql
    ports:
      - 3000:3000

  mysql:
    container_name: sandbox-ecs-mysql
    image: mysql
    env_file: docker/.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
