cluster: sandbox

auto_deploy:
  branches:
    master: production

ecs_containers:
  default: &default
    rails:
      build: ..
    fluentd:
      build: ../etc/docker/fluentd

  development:
    <<: *default

  staging:
    <<: *default

  production:
    <<: *default
