cluster: sandbox

auto_deploy:
  branches:
    master: production

ecs_containers:
  default: &default
    rails2:
      build: ..

  development:
    <<: *default

  staging:
    <<: *default

  production:
    <<: *default
