family: sandbox-development
task_role_arn: ''
network_ode: bridge
container_definitions:
- name: rails
  image: 879837989888.dkr.ecr.ap-northeast-1.amazonaws.com/sandbox-ecs-rails-development:{{tag}}
  memory: 384
  port_mappings:
  - container_port: 3000
    host_port: 0
    protocol: tcp
  essential: true
  environment:
  - name: MYSQL_ROOT_PASSWORD
    value: 'passw0rd'
  - name: RAILS_ENV
    value: development
  - name: SECRET_KEY_BASE
    value: wasq6bvp9ugf46eawmt2k6n855optipw2afqirfpemozz6jbxvdnzemgfsnjf2pdfvdx9t2lzh9hwp2g9nus2il2q81y170idxmdezeqj1jtm6llnkny3igxeyha7ujj
  readonly_root_filesystem: false
  log_configuration:
    log_driver: awslogs
    options:
      awslogs-group: sandbox-rails-development
      awslogs-region: ap-northeast-1
      awslogs-stream-prefix: application
