family: sandbox-ecs-production
taskRoleArn: ''
networkMode: bridge
containerDefinitions:
- name: rails
  image: 879837989888.dkr.ecr.ap-northeast-1.amazonaws.com/sandboxecs-rails-production:latest
  memory: 128
  portMappings:
  - containerPort: 3000
    hostPort: 0
    protocol: tcp
  essential: true
  environment:
  - name: MYSQL_ROOT_PASSWORD
    value: ''
  - name: RAILS_ENV
    value: production
  - name: SECRET_KEY_BASE
    value: c04b633d16a360c78852efd6ac53dac0a07abf94982ba02e3bd95a3bd9f021222e134172c9b356ef0a1fcc285c8910708002b510b5c4a54e908a39617ad6d81c
  readonlyRootFilesystem: false
  logConfiguration:
    logDriver: awslogs
    options:
      awslogs-group: sandbox-ecs-rails-production
      awslogs-region: ap-northeast-1
      awslogs-stream-prefix: application

