family: sandbox-production
task_role_arn: ''
network_ode: bridge
container_definitions:
- name: rails
  image: 879837989888.dkr.ecr.ap-northeast-1.amazonaws.com/sandbox-ecs-rails-production:{{tag}}
  memory: 384
  port_mappings:
  - container_port: 3000
    host_port: 0
    protocol: tcp
  essential: true
  environment:
  - name: MYSQL_ROOT_PASSWORD
    value: 'passw0rd'
  - name: RAILS_ENV
    value: production
  - name: SECRET_KEY_BASE
    value: c04b633d16a360c78852efd6ac53dac0a07abf94982ba02e3bd95a3bd9f021222e134172c9b356ef0a1fcc285c8910708002b510b5c4a54e908a39617ad6d81c
  readonly_root_filesystem: false
  log_configuration:
    log_driver: fluentd
    options:
      # fluentd-address: internal-log-production-113789567.ap-northeast-1.elb.amazonaws.com:24224
      fluentd-address: 172.16.3.110:24224
      tag: docker.sandbox_ecs_rails_production
      fluentd-async-connect: "true"
