family: sandbox-staging
task_role_arn: ''
network_ode: bridge
container_definitions:
- name: rails
  image: 879837989888.dkr.ecr.ap-northeast-1.amazonaws.com/sandbox-ecs-rails-staging:{{tag}}
  memory: 384
  port_mappings:
  - container_port: 3000
    host_port: 0
    protocol: tcp
  essential: true
  environment:
  - name: MYSQL_ROOT_PASSWORD
    value: 'passw0rd'
  - name: RAILS_ENV
    value: staging
  - name: SECRET_KEY_BASE
    value: 124f3xzg0k3izywaekoj1hprjqy2infg14ekbzp7yb6cvjr9ycl6g4kpoapq7ykk8evciev92ahpogo2p6u84fb1rx9ye1j3495y432jhaw5ihzgbj6za7dsvs6h1xyv
  - name: RAILS_LOG_TO_STDOUT
    value: enabled
  readonly_root_filesystem: false
  log_configuration:
    log_driver: fluentd
    options:
      fluentd-address: internal-log-production-113789567.ap-northeast-1.elb.amazonaws.com:24224
      fluentd-async-connect: "true"
      tag: docker.sandbox_ecs_rails_staging
