family: sandbox-staging
task_role_arn: ''
network_ode: bridge
container_definitions:
- name: rails
  image: 879837989888.dkr.ecr.ap-northeast-1.amazonaws.com/sandboxecs-rails-staging:latest
  memory: 512
  port_mappings:
  - container_port: 3000
    host_port: 0
    protocol: tcp
  essential: true
  environment:
  - name: MYSQL_ROOT_PASSWORD
    value: ''
  - name: RAILS_ENV
    value: staging
  - name: SECRET_KEY_BASE
    value: 124f3xzg0k3izywaekoj1hprjqy2infg14ekbzp7yb6cvjr9ycl6g4kpoapq7ykk8evciev92ahpogo2p6u84fb1rx9ye1j3495y432jhaw5ihzgbj6za7dsvs6h1xyv 
  readonly_root_filesystem: false
  log_configuration:
    log_driver: awslogs
    options:
      awslogs-group: sandbox-rails-staging
      awslogs-region: ap-northeast-1
      awslogs-stream-prefix: application

